name: BuildAndTestUbuntu-Debug

on:
  [push, pull_request]

jobs:
  ubuntu_build_pymeshlab_debug:
    name: Build PyMeshLab (Ubuntu-Debug)
    runs-on: ubuntu-16.04 #in order to deploy, need to use oldest supported version
    strategy:
      matrix:
        pyversion: [3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: checkout sub-submodule vcg
      run: |
        cd meshlab
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: xmlpatterns
    - name: Install Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install dependencies
      run: |
       sudo apt-get install -y mesa-common-dev libglu1-mesa-dev 
    - name: Environment variables
      id: envs
      run: |
        cd meshlab
        echo  ::set-output name=meshlab_commit::$(git rev-parse --short HEAD)
    - name: Cache MeshLab Build
      id: cache-meshlab-build
      uses: actions/cache@v2
      with:
        path: pymeshlab/lib
        key: ${{ runner.os }}-meshlab_debug-${{steps.envs.outputs.meshlab_commit}}
    - name: Build MeshLab
      if: steps.cache-meshlab-build.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y libgmp-dev libxkbcommon-x11-0 patchelf
        sh install/linux/build_meshlab_debug.sh
    - name: Build PyMeshLab ${{ matrix.pyversion }}
      run: |
        export PYTHON_VERSION=${{ matrix.pyversion }}
        sh install/linux/build_pymeshlab_debug.sh
    - name: Upload PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}_debug
      uses: actions/upload-artifact@v2
      with:
        name: PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}_debug
        path: pymeshlab/
  
  
  ubuntu_tests_debug:
    name: Test PyMeshLab (Ubuntu-Debug)
    needs: ubuntu_build_pymeshlab_debug
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Download PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}_debug
      uses: actions/download-artifact@v2
      with:
        name: PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}_debug
        path: pymeshlab/
    - name: Install Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Run Tests ${{ matrix.pyversion }}
      run: |
        pip install pytest
        pytest -s pymeshlab
    
