name: BuildAndTestUbuntu

on:
  [push, pull_request]

jobs:
  ubuntu_build_pymeshlab:
    name: Build PyMeshLab (Ubuntu)
    runs-on: ubuntu-16.04 #in order to deploy, need to use oldest supported version

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: checkout sub-submodule vcg
      run: |
        cd meshlab
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: xmlpatterns
    - name: Install dependencies
      run: |
       sudo add-apt-repository ppa:deadsnakes/ppa -y
       sudo apt-get update
       sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libgmp-dev
       sudo apt-get install -y libxkbcommon-x11-0 patchelf python3.5-dev python3.6-dev python3.8-dev
    - name: Environment variables
      id: envs
      run: |
        cd meshlab
        echo  ::set-output name=meshlab_commit::$(git rev-parse --short HEAD)
    - name: Cache MeshLab Build
      id: cache-meshlab-build
      uses: actions/cache@v2
      with:
        path: PyMeshLab
        key: ${{ runner.os }}-meshlab-${{steps.envs.outputs.meshlab_commit}}
    - name: Build MeshLab
      if: steps.cache-meshlab-build.outputs.cache-hit != 'true'
      run: |
        sh install/linux/build_meshlab.sh
    - name: Build PyMeshLab 3.5
      run: |
        export PYTHON_VERSION=$(python3.5 -c 'import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))')
        sh install/linux/build_pymeshlab.sh
    - name: Build PyMeshLab 3.6
      run: |
        export PYTHON_VERSION=$(python3.6 -c 'import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))')
        sh install/linux/build_pymeshlab.sh
    - name: Build PyMeshLab 3.8
      run: |
        export PYTHON_VERSION=$(python3.8 -c 'import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))')
        sh install/linux/build_pymeshlab.sh
    - name: Upload PyMeshLab
      uses: actions/upload-artifact@v1
      with:
        name: PyMeshLab
        path: PyMeshLab/
  
  
  ubuntu_tests:
    name: Test PyMeshLab (Ubuntu)
    needs: ubuntu_build_pymeshlab
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download PyMeshLab Linux
      uses: actions/download-artifact@v1
      with:
        name: PyMeshLab
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3.5 python3.6 python3.8
    - name: Run Tests 3.5
      run: |
        python3.5 run_tests.py
    - name: Run Tests 3.6
      run: |
        python3.8 run_tests.py
    - name: Run Tests 3.8
      run: |
        python3.8 run_tests.py
    
