name: BuildUbuntu

on:
  [push, pull_request]

jobs:
  ubuntu_build_meshlab:
    name: Build PyMeshLab (Ubuntu)
    runs-on: ubuntu-16.04 #in order to deploy, need to use oldest supported version

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: xmlpatterns
    - name: Install dependencies
      run: |
       sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libglew-dev libeigen3-dev libgmp-dev
       sudo apt-get install -y libxkbcommon-x11-0 patchelf
    - name: Build MeshLab
      run: |
        sh install/linux/build_meshlab.sh
    - name: Upload PyMeshLab
      uses: actions/upload-artifact@v1
      with:
        name: PyMeshLab
        path: PyMeshLab/
