name: BuildAndTestMacOS

on:
  [push, pull_request]

jobs:
  macos_build_pymeshlab:
    name: Build PyMeshLab (MacOS)
    runs-on: macos-latest
    strategy:
      matrix:
        pyversion: [3.2, 3.4, 3.6, 3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: checkout sub-submodule vcg
      run: |
        cd meshlab
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: xmlpatterns
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: /Users/runner/.pyenv/versions/${{matrix.pyversion}}.0
        key: ${{ runner.os }}-cache_pyenv-${{matrix.pyversion}}
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true' 
      run: |
       brew install pyenv
       pyenv install ${{ matrix.pyversion }}.0
    - name: Environment variables
      id: envs
      run: |
        cd meshlab
        echo  ::set-output name=meshlab_commit::$(git rev-parse --short HEAD)
    - name: Cache MeshLab Build
      id: cache-meshlab-build
      uses: actions/cache@v2
      with:
        path: PyMeshLab
        key: ${{ runner.os }}-meshlab-${{steps.envs.outputs.meshlab_commit}}
    - name: Build MeshLab
      if: steps.cache-meshlab-build.outputs.cache-hit != 'true'
      run: |
        brew install libomp
        sh install/macos/build_meshlab.sh
    - name: Build PyMeshLab ${{ matrix.pyversion }}
      run: |
        export PYTHON_VERSION=${{ matrix.pyversion }}
        sh install/macos/build_pymeshlab.sh
    - name: Upload PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}
      uses: actions/upload-artifact@v1
      with:
        name: PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}
        path: PyMeshLab/
  
  
  macos_tests:
    name: Test PyMeshLab (MacOS)
    needs: macos_build_pymeshlab
    runs-on: macos-latest
    strategy:
      matrix:
        pyversion: [3.2, 3.4, 3.6, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Download PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}
      uses: actions/download-artifact@v1
      with:
        name: PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}
        path: PyMeshLab/
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: /Users/runner/.pyenv/versions/${{matrix.pyversion}}.0
        key: ${{ runner.os }}-cache_pyenv-${{matrix.pyversion}}
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true' 
      run: |
       brew install pyenv
       pyenv install ${{ matrix.pyversion }}.0
    - name: Run Tests ${{ matrix.pyversion }}
      run: |
        /Users/runner/.pyenv/versions/${{matrix.pyversion}}.0/bin/python${{ matrix.pyversion }} run_tests.py
    
